### PR TITLE
fix bug with submitting a form

### PR DESCRIPTION
**Pull request by Kris-Simpson**
This changes fix form submitting by clicking on aligning buttons #4

### CODE REVIEW

**Comment by Kris-Simpson** [comment]
@kaaaaaaaaaaai should I do something else in this PR? Or this is enough for the fix?

**Comment by michaelcais** [comment]
@kaaaaaaaaaaai Can you merge this fix to the main branch?

**Comment by dimuska139** [comment]
Merge it please

**Comment by Charlesllamas** [comment]
@kaaaaaaaaaaai Merge it please

**Comment by ranuarga** [comment]
@kaaaaaaaaaaai Merge it, please

**Comment by brtchkv** [comment]
@kaaaaaaaaaaai can you merge it, please?

**Comment by kaaaaaaaaaaai** [comment]
waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaait.

coooooooooooooooooooome onneeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Pull request merged**
